### ISSUE TITLE
Documentation is wrong

### ISSUE THREAD

**Issue by patrickyan** [bennylope/smartystreets.py#2]
It says to do

```
client = SmartyStreets(AUTH_ID, AUTH_TOKEN)
```

when you are supposed to do

```
from smartystreets import Client
client = Client(AUTH_ID, AUTH_TOKEN)
```

**Comment by bennylope** [comment]
Thanks - if you see an issue like this here or in any other repo, a pull request in addition to or in lieu of an issue will be warmly welcomed!
