### ISSUE TITLE
Documentation isn't updated on pypi.python.org

### ISSUE THREAD

**Issue by camiblanch** [bennylope/smartystreets.py#3]
This is similar to a previous issue. The documentation needs to be updated [here](https://pypi.python.org/pypi/smartystreets.py) to match the documentation here on GitHub.
    `from smartystreets import Client`
    `client = Client(AUTH_ID, AUTH_TOKEN)`
instead of
`client = SmartyStreets(AUTH_ID, AUTH_TOKEN)`

This caused confusion as seen on [stackoverflow.com](http://stackoverflow.com/questions/35183887/how-to-use-smartystreets-with-python)

**Comment by bennylope** [comment]
That's a function of the release cycle (now on [0.3.0](https://pypi.python.org/pypi/smartystreets.py)). What's on PyPI is based on what's in the given release, what's in the repo is subject to change with additional development.
